MUL-1029: BTC tx to P2SH address
Appscrunch/Multy-Core pull request #61
Opened 2018-03-18 22:59 UTC by PashaKlybik

-make transaction with PubScript <P2SH> destination
 -make transaction with PubScript <P2SH-segwit-addresses> destination
Also task MUL-1066: add tests with P2SH addresses testnet/mainne

2018-03-18 22:59 UTC, PashaKlybik commented
@Enmk

2018-03-19 07:57 UTC, Enmk commented on multy_core/src/api/account.cpp
> +                    THROW_EXCEPTION("BTC: Only P2PKH and P2SH addresses are supported for now.");
Please update the message:
```
THROW_EXCEPTION("Not supported address type, only P2PKH and P2SH are supported.") << " Address type: " << address_type;
```

2018-03-19 08:09 UTC, Enmk requested changes
Minor fixes + add more test cases

2018-03-19 08:09 UTC, Enmk commented on multy_test/test_bitcoin_transaction.cpp
> +    HANDLE_ERROR(make_account(
```
        AccountPtr account = make_account(BLOCKCHAIN_BITCOIN,
                "cQeGKosJjWPn9GkB7QmvmotmBbVg1hm8UjdN6yLXEWZ5HAcRwam7");
```

2018-03-19 08:09 UTC, Enmk commented on multy_test/test_bitcoin_transaction.cpp
> +    TransactionPtr transaction = make_transaction_from_template(TEST_TX);
```
        transaction = make_transaction_from_template(temp, TEST_TX,
                account->get_private_key());
```

2018-03-19 08:09 UTC, Enmk commented on multy_test/test_bitcoin_transaction.cpp
> +}
Please add a test that verifies destination address validation.
2 cases when validation should pass: 
* P2PKH 
* P2SH
and one case where it fails:
* some bogus address.

2018-03-19 08:09 UTC, Enmk commented on multy_core/src/bitcoin/bitcoin_transaction.cpp
> +    OP_CHECKSIG =0xAC,
```OP_CHECKSIG =<MISSING SPACE HERE>0xAC,```

2018-03-19 14:54 UTC, Enmk approved these changes
Ok

2018-03-20 03:59 UTC, Enmk reviewed
Ok

2018-03-20 04:20 UTC, merged